markdown: kramdown
title: 18F Project Guide
description: Resources and advice for managing projects at 18F.
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- README.md
- go

permalink: pretty
highlighter: rouge
kramdown:
  auto_ids: true

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: 18F Product Chapter
  url: https://18f.gsa.gov

github:
  organization: 18F
  repository: project-guide
  default_branch: master

collections:
  pages:
    output: true
    permalink: /:path/

generate_nodes: true
flat_namespace: true

gems:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Welcome to leading a project
  blurb: |
    This is a guide to a project lead’s responsibilities and decisions at the beginning of a project.
  url: welcome/
  internal: true
  generated: true
  children:
  - text: About leading 18F projects
    url: about-leading-18f-projects/
    internal: true
  - text: License
    url: license/
    internal: true
- text: Starting a new project
  blurb: |
    How to start a new project at 18F.
  url: starting-a-new-project/
  internal: true
  generated: true
  children:
  - text: First steps
    url: first-steps
    internal: true
   - text: Choose your major processes and tools
    url: choose-your-tools
    internal: true
   - text: Communication and rituals
    url: communication-and-rituals
    internal: true
- text: Kick off
  blurb: |
    Plan a kick off workshop with your partner
  url: plan-a-kick-off/
  internal: true
  generated: true
  children:
  - text: Who to invite
    url: who-to-invite
    internal: true
  - text: What to cover, part 1: Share
    url: what-to-cover-share
    internal: true
  - text: What to cover, part 2: Gaining insight
    url: what-to-cover-insight
    internal: true
- text: Additional resources
  blurb: |
    Additional helpful guides and examples.
  url: additional-resources/
  internal: true
  generated: true
  children:
  - text: Resources
    url: resources
    internal: true



repos:
- name: 18F Project Guide
  description: Main repository
  url: https://github.com/18F/project-guide

google_analytics_ua: 


# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true
  placeholder: Search
  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
