version: '2'
services:
  app:
    build: .
    working_dir: /project-guide
    command: bash -c 'bundle install && jekyll serve --force_polling -H 0.0.0.0 -P 4000'
    stop_signal: SIGKILL
    ports:
      - 4000:4000
    volumes:
      - .:/project-guide
      - root:/root/
      - bundle:/usr/local/bundle/
volumes:
  root:
  bundle:
